version: '3.2'

services:
    php:
        image: composer:2.3
        volumes:
            - .:/app
            - ${COMPOSER_HOME:-$HOME/.composer}:/tmp
        networks:
            - app

networks:
    app:
        driver: bridge
